<Project Sdk="Microsoft.NET.Sdk.Worker">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UserSecretsId>dotnet-simple_dotnet_worker-24fb8354-dc67-4ff4-816e-acff0af0a6c7</UserSecretsId>
    <RootNamespace>simple_dotnet_worker</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="AWSSDK.DynamoDBv2" Version="4.0.102.1" />
    <PackageReference Include="AWSSDK.Extensions.NETCore.Setup" Version="4.0.100.7" />
    <PackageReference Include="AWSSDK.S3" Version="4.0.101.6" />
    <PackageReference Include="AWSSDK.SQS" Version="4.0.100.7" />
    <PackageReference Include="Microsoft.Extensions.Hosting" Version="8.0.0" />
  </ItemGroup>
</Project>
